

    <h1> Contact Us<br></h1>
    <h2> Some of us like to travel<br></h2>
    <h2> Some of us like to bake<br></h2>
    <h2> So what better way to express our love of both, through exploring international bakes, cakes and puds!<br></h2>
    <h2> If you need to get in touch, just fill out the form below.</h2>
    <p>
    </p>

<form method="POST" action="contactus.php">
  <!--  <input type= "title" class="form-control" placeholder= "Title" rows="1" cols="50"></textarea><br>
  //  <input type= "body" class="form-control input-lg" placeholder="Write post here..." rows="15" cols="100"></textarea><br>
  //  <input type= "author_id" class="form-control" placeholder="Author" rows="1" cols="100"></textarea>
  //  <input class="btn btn-default" type="Post" value="Post">
</form> -->

<!-- HTML Form (wrapped in a .bootstrap-iso div) -->
<div class="bootstrap-iso">
 <div class="container-fluid">
  <div class="row">
   <div class="col-md-6 col-sm-6 col-xs-12">
    <form method="post" action="">
     <div class="form-group ">
      <label class="control-label requiredField" for="Title">
        <span>
         Email:
       </span class=asteriskField>
       *
       </label>

       <input class="form-control" id="Title" name="Title" type="text"/>
      </div>
      <div class="form-group ">
       <label class="control-label requiredField" for="Post">
       Title:
       <span class="asteriskField">

       </span>
      </label>
      <input class="form-control" id="Title" name="Title" type="text"/>
     </div>
     <div class="form-group ">
      <label class="control-label requiredField" for="Post">
        Name:
        <span>

        </span>
       </label>
       <input class="form-control" id="Title" name="Title" type="text"/>
      </div>
      <div class="form-group ">
       <label class="control-label requiredField" for="Post">
        Phone Number:
        <span>

        </span>
       </label>
       <input class="form-control" id="Title" name="Title" type="text"/>
      </div>
      <div class="form-group ">
       <label class="control-label requiredField" for="Post">
       Your message:
       <span>
       </span>
      </label>
      <textarea class="form-control" cols="20" id="Post" name="Post" placeholder="Write Text here" rows="10"></textarea>
     </div>
     <div class="form-group ">
      <label class="control-label requiredField" for="Author ID">
      <span>

     </div>
     <div class="form-group">
      <div>
       <button class="btn btn-info btn-lg btn-block" name="submit" type="submit">
        Submit
       </button>
       <p>
