<!DOCTYPE html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
  <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
  <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso16.css" />

  <!-- Inline CSS based on choices in "Settings" tab -->
  <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: #ffffff !important;} .asteriskField{color: red;}


body {
  margin: 1em;
}

ul#nav {
  list-style-type: none;
}

ul#nav li {
  float: left;
}


ul#nav li a {
    display: block;
    text-align: center;
    padding: 16px;
    text-decoration: none;
}

h1 {
  margin: 2em;
}


textarea {
  margin: 2em;
  width: 50em;
  height: 5em;
}
  </style>


<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <title>Around the world in 80 bakes!</title>
</head>
  <body>
    <div class="header">
      <hr>
    </div>
    <ul id="nav">
          <li class="<?php echo ($_SERVER['PHP_SELF'] == "/index.php" ? "active" : "");?>">
        <a href="index.php">Home</a>
      </li>
          <li class="<?php echo ($_SERVER['PHP_SELF'] == "/login.php" ? "active" : "");?>">
        <a href="login.php">Sign In</a>
        </li>

        <li class="<?php echo ($_SERVER['PHP_SELF'] == "/register.php" ? "active" : "");?>">
      <a href="register.php">Register</a>
    </li>

        <li class="<?php echo ($_SERVER['PHP_SELF'] == "/contactus.php" ? "active" : "");?>">
        <a href="contactus.php">Contact Us</a>
      </li>

        <li class="<?php echo ($_SERVER['PHP_SELF'] == "/archivepages.php" ? "active" : "");?>">
      <a href="archivepages.php">Archive Pages</a>
        </li>
        <li class="<?php echo ($_SERVER['PHP_SELF'] == "/view3.php" ? "active" : "");?>">
        <a href="view.php?id=2">Latest Article</a>
      </li>
</ul>
  <hr>

  </li>
